# Generated by Django 4.2 on 2023-10-09 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='identifier_system',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='identifier_value',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[1-9][0-9]*$')]),
        ),
    ]
